Vagrant.configure("2") do |config|
  # 定义虚拟机的通用设置
  config.vm.box = "ubuntu2004@offical"
  # 定义资源配置哈希
  vm_configs = {
    master_cf: {
      ip: "10.0.12.10",
      token: "k3s_token"
    }
  }

  # 定义主节点
  config.vm.define "master" do |master|
    master.vm.hostname = "master"
    master.vm.network "private_network", ip: "10.0.12.10"
    master.ssh.insert_key = false
    # master.ssh.username = "vagrant"
    # master.ssh.password = "vagrant"
    master.vm.synced_folder "./", "/vagrant"
    master.vm.provider "virtualbox" do |vb|
      vb.name = "master" 
      vb.memory = "1500"   
      vb.cpus = 2
      vb.gui = false
    end

    master.vm.provision "shell", name: "install_k8s_master", path: "install_k8s_master.sh", privileged: true do |e|
      # 设置环境变量
      e.env = { 
        "ip": vm_configs[:master_cf][:ip],
        "token": vm_configs[:master_cf][:token]
      }
    end
  end

  config.vm.define "worker1" do |worker|
    worker.vm.hostname = "worker1"
    worker.vm.network "private_network", ip: "10.0.12.20"
    worker.ssh.insert_key = false
    worker.vm.synced_folder "./", "/vagrant"
    worker.vm.provider "virtualbox" do |vb|
      vb.name = "worker1" 
      vb.memory = "512"   
      vb.cpus = 1
      vb.gui = false
    end
    worker.vm.provision "shell", name: "install_k8s_worker", path: "install_k8s_worker.sh", privileged: true do |e|
      # 设置环境变量
      e.env = { 
        "ip": "10.0.12.20",
        "master_ip": vm_configs[:master_cf][:ip],
        "token": vm_configs[:master_cf][:token]
      }
    end
  end
end
